### ISSUE TITLE
Determine most appropriate options for "component" and "program"

### ISSUE THREAD

**Issue by Japh** [Japh/stream-to-papertrail#11]
Originally raised in #9 is the point that "component" and "program", while they are the terms used by Papertrail, aren't necessarily inherently obvious in their usage and purpose in the context of Stream.

I'd like to make them use sensible defaults, but also be a little configurable.

Seeing as you can log data to Papertrail from a range of sources relating to your web site / app, these things kind of need to make sense in that setup too.

The main use is for filtering while viewing logs.

Currently, I've set the defaults to "wordpress" and "stream". But that probably doesn't actually make sense for most uses.

Imagine that you also have nginx logs being sent there, PHP logs, general system logs, etc.

Perhaps better defaults would be to set the "component" to the hostname for the WordPress site (e.g. `mysite.com`) and "program" to the Stream connector value?

This would give you entries like:

```
Sep 08 15:20:34 japh.local taxonomies: {"object_id":292,"site_id":1,"blog_id":1,"user_id":1,"user_role":"administrator","created":"2015-09-08T05:20:33.862+0000","summary":"\"external\" tags created","connector":"Taxonomies","context":"product_type","action":"created","ip":"172.28.128.1","meta":{"term_name":"external","taxonomy_label":"tags","term_id":"292","taxonomy":"product_type","term_parent":"0","user_meta":{"user_email":"japhie@gmail.com","display_name":"japheth","user_login":"japheth","user_role_label":"Administrator","agent":""}},"record_id":61}
Sep 08 15:21:15 japh.local posts: {"object_id":5009,"site_id":1,"blog_id":1,"user_id":1,"user_role":"administrator","created":"2015-09-08T05:21:15.614+0000","summary":"\"Shop\" page published","connector":"Posts","context":"page","action":"updated","ip":"172.28.128.1","meta":{"post_title":"Shop","singular_name":"page","post_date":"2015-09-08 15:21:15","post_date_gmt":"2015-09-08 05:21:15","new_status":"publish","old_status":"new","user_meta":{"user_email":"japhie@gmail.com","display_name":"japheth","user_login":"japheth","user_role_label":"Administrator","agent":""}},"record_id":62}
Sep 08 15:21:15 japh.local woocommerce: {"object_id":0,"site_id":1,"blog_id":1,"user_id":1,"user_role":"administrator","created":"2015-09-08T05:21:15.698+0000","summary":"\"Shop Page\" setting updated","connector":"Woocommerce","context":"products","action":"updated","ip":"172.28.128.1","meta":{"label":"Shop Page","type":"setting","page":"wc-settings","tab":"products","section":"display","option":"woocommerce_shop_page_id","old_value":"","value":"5009","user_meta":{"user_email":"japhie@gmail.com","display_name":"japheth","user_login":"japheth","user_role_label":"Administrator","agent":""}},"record_id":63} 
```

Where `japh.local` and `connector_name` (e.g. `woocommerce`) would be clickable to filter based on only events with a matching component or program value.

Seeing as "component" seems to be intended for use as a hostname, it might also make sense to prefix the "program" value with `stream-` or something (maybe even `wordpress-` or `wp-`). You may also be logging things with `japh.local` as the component from nginx or PHP, etc.

This was a bit rambly, but basically I'm interested in people's thoughts on the most sensible way to go here.

Essentially by defaulting to hostname and `stream` + connector name, it may be that we can do away with these options altogether.

Any thoughts, @sirjonathan @lukecarbis @troy?

**Comment by troy** [comment]
> while they are the terms used by Papertrail

Tiny point of clarification. Papertrail uses the terms "sender name" and "program name." This PHP snippet uses the terms you mentioned because they fit better in the situation that the PHP snippet was written for, where an app/program is logging from multiple components. Not what I'd call universal though :)

> Perhaps better defaults would be to set the "component" to the hostname for the WordPress site (e.g. mysite.com) and "program" to the Stream connector value?

I'd strongly support this and it's a better use of the fields. I'd actually consider renaming `component` to `sender_name` and using the return value of `gethostname()` by default. That way, if a single WP site is hosted on >1 systems, the sender will be unique to reach.

**Comment by Japh** [comment]
Perfect! Thanks for the clarification, @troy!
