### ISSUE TITLE
Clarify Papertrail settings

### ISSUE THREAD

**Issue by sirjonathan** [Japh/stream-to-papertrail#9]
"Component" and "Program", in particular, aren't clear. I suggest adding explanations to the Papertrail settings panel as well as an "intro" paragraph with a link to Papertrail to sign-up.

**Comment by Japh** [comment]
Great suggestion, thanks! To be honest, I'm still trying to ascertain the best use for the "Component" and "Program" options. In the meantime, I can at least explain where they'll appear in the log entries and what Papertrail does with them.

**Comment by troy** [comment]
I'll let @japh address whether or how the docs may evolve, but for anyone else who finds this, what's called `program` and `component` are the syslog sender hostname and syslog tag/program fields.

They're colorized orange and blue in Papertrail ([screenshot](http://help.papertrailapp.com/kb/how-it-works/event-viewer/#context)) and can be clicked to "pivot" and show surrounding context (think `grep -A/B/C`), like to see output from only a specific component.

**Comment by Japh** [comment]
@troy There's a similar concept to this in Stream already, so perhaps I can tweak things to use that instead. Might make more sense.

Just have to think of s way that's also friendly to any other logging that could also be sent alongside. That was my thinking for the current defaults anyway.

**Comment by Japh** [comment]
Going to close this in favour of #11. If the options end up staying, then will re-open this and deal with clarification  :smile:
